version: '3.7'

services:
  qisat_www:
    build:  "./"
    restart: always
    container_name : qisat_www
    volumes:
      - ./html:/var/www/html/teste
    ports:
      - '${WWW_HOST_PORT}:${WWW_CTNR_PORT}'
      - '${SSL_HOST_PORT}:${SSL_CTNR_PORT}'